printWidth: 120
tabWidth: 4
semi: true
singleQuote: true
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid

overrides:
- files: "*.json"
  options:
    parser: json
    printWidth: 1000
- files: "*.md"
  options:
    parser: markdown
- files: "*.less"
  options:
    parser: css